[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.llamahub]
contains_example = false
import_path = "llama_index.graph_stores.tidb"

[tool.llamahub.class_authors]
TiDBGraphStore = "llama-index"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.8"

[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "llama-index graph stores tidb integration"
exclude = ["**/BUILD"]
license = "MIT"
name = "llama-index-graph-stores-tidb"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
tidb-vector = "^0.0.9"
PyMySQL = "^1.1.1"
SQLAlchemy = "^2.0.30"
llama-index-core = "^0.10.40"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
mypy = "^1.10.0"
pre-commit = "3.2.0"
pytest = "7.2.1"

[tool.poetry.group.dev.dependencies.black]
extras = ["jupyter"]
version = "<=23.9.1,>=23.7.0"

[tool.poetry.group.dev.dependencies.codespell]
extras = ["toml"]
version = ">=v2.2.6"

[[tool.poetry.packages]]
include = "llama_index/"
